AmazonMail/Models/BLACKLIST.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLACKLIST
    {
        public int ID { get; set; }
        public string EMAIL { get; set; }
        public System.DateTime TIMESTAMP { get; set; }
        public string REASON { get; set; }
    }
}

AmazonMail/Controllers/BlackListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AmazonMail.Models;
using PagedList;



namespace AmazonMail.Controllers
{
    public class BlackListController : Controller
    {
        private AmazonDBModel db = new AmazonDBModel();

        // GET: /BlackList/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "date_asc" : "";
            ViewBag.ReceiverSortParm = sortOrder == "receiver" ? "receiver_desc" : "receiver";         
        
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var blacklist = from b in db.BLACKLIST select b;
         
            if (!String.IsNullOrEmpty(searchString))
            {
                blacklist = blacklist.Where(s => s.EMAIL.Contains(searchString)
                                       || s.EMAIL.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "receiver_desc":
                    blacklist = blacklist.OrderByDescending(s => s.EMAIL);
                    break;
                case "receiver":
                    blacklist = blacklist.OrderBy(s => s.EMAIL);
                    break;              
                case "date_asc":
                    blacklist = blacklist.OrderBy(s => s.EMAIL);
                    break;
                default:
                    blacklist = blacklist.OrderByDescending(s => s.EMAIL);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);            
            var mes = blacklist.ToPagedList(pageNumber, pageSize);
            return View(mes);            
        }

        
        public ActionResult Search(string currentFilter, string searchString, int? page)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        public ActionResult Find(string currentFilter, string searchString, int? page)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            searchString = searchString.Trim().ToLower().Replace(Environment.NewLine, "").Replace(" ", "");
            ViewBag.CurrentFilter = searchString;
            var emails = searchString.Split(',');
            var blacklist = db.BLACKLIST.Where(b => emails.Contains(b.EMAIL.Trim().ToLower()));
            blacklist = blacklist.OrderByDescending(s => s.EMAIL);
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var mes = blacklist.ToPagedList(pageNumber, pageSize);
            return View(mes);         
            
        }

        // GET: /BlackList/Details/5
        public ActionResult Details(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BLACKLIST blacklist = db.BLACKLIST.Find(id);
            if (blacklist == null)
            {
                return HttpNotFound();
            }
            return View(blacklist);
        }

        // GET: /BlackList/Create
        public ActionResult Create()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View();
        }

        // POST: /BlackList/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,EMAIL,TIMESTAMP,REASON")] BLACKLIST blacklist)
        {
            if (ModelState.IsValid)
            {
                db.BLACKLIST.Add(blacklist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blacklist);
        }



       

    // POST: /BlackList/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,EMAIL,TIMESTAMP,REASON")] BLACKLIST blacklist)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (ModelState.IsValid)
            {
                db.Entry(blacklist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blacklist);
        }

        // GET: /BlackList/Delete/5
        public ActionResult DeleteAll(string mailIdentifiers)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (mailIdentifiers == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var emails = mailIdentifiers.Split(',');
            var blacklist = db.BLACKLIST.Where(b => emails.Contains((b.ID.ToString())));
            db.BulkDelete(blacklist, options => options.BatchSize = 100);
            db.SaveChanges();  
            return RedirectToAction("Search");
        }

        public ActionResult Delete(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BLACKLIST blacklist = db.BLACKLIST.Find(id);
            if (blacklist == null)
            {
                return HttpNotFound();
            }
            return View(blacklist);
        }

        // POST: /BlackList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            BLACKLIST blacklist = db.BLACKLIST.Find(id);
            db.BLACKLIST.Remove(blacklist);
            db.SaveChanges();
            if (User.IsInRole("Admin"))
                return RedirectToAction("Index");
            else
                return RedirectToAction("Search");
        }            

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AmazonMail/Views/BlackList/Create.cshtml
@model AmazonMail.Models.BLACKLIST

@{
    
    ViewBag.Title = "Black List";   
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Lista negra</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.EMAIL, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL)
                    @Html.ValidationMessageFor(model => model.EMAIL)
                </div>
            </div>    
            <div class="form-group">
                @Html.LabelFor(model => model.TIMESTAMP, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBox("Timestamp", System.DateTime.Now)
                    @Html.ValidationMessageFor(model => model.TIMESTAMP)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.REASON, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.REASON)
                    @Html.ValidationMessageFor(model => model.REASON)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Volver a buscar", "Index")
    </div>
</body>
</html>

AmazonMail/Views/BlackList/Delete.cshtml
@model AmazonMail.Models.BLACKLIST

@{
    
    ViewBag.Title = "Black List";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>¿Está seguro de que quiere eliminar una entrada de la lista negra?</h3>
    <div>
        <h4>Lista negra</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayName("Email")
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>
    
            <dt>
                @Html.DisplayName("Fecha y hora")
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TIMESTAMP)
            </dd>
    
            <dt>
                @Html.DisplayName("Causa")
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.REASON)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-default" />                 
            </div>
        }
    </div>    
     @Html.ActionLink("Buscar otra dirección", "Search")
   

</body>
</html>

AmazonMail/Views/BlackList/Details.cshtml
@model AmazonMail.Models.BLACKLIST

@{
   
    ViewBag.Title = "Black List";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>BLACKLIST</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.EMAIL)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.EMAIL)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.TIMESTAMP)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.TIMESTAMP)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.REASON)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.REASON)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

AmazonMail/Views/BlackList/Edit.cshtml
@model AmazonMail.Models.BLACKLIST

@{
    
    ViewBag.Title = "Black List";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Editar</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Lista negra</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.ID)
    
            <div class="form-group">
                @Html.Label("Email", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL)
                    @Html.ValidationMessageFor(model => model.EMAIL)
                </div>
            </div>
    
            <div class="form-group">
                @Html.Label("Fecha y hora", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TIMESTAMP)
                    @Html.ValidationMessageFor(model => model.TIMESTAMP)
                </div>
            </div>
    
            <div class="form-group">
                @Html.Label("Causa", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.REASON)
                    @Html.ValidationMessageFor(model => model.REASON)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Volver a buscar", "Search")
    </div>
</body>
</html>

AmazonMail/Views/BlackList/Find.cshtml
@model IEnumerable<AmazonMail.Models.BLACKLIST>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{    
    ViewBag.Title = "Black List";
    var pagedlist = (IPagedList)Model;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lista negra</title>
</head>
<body>
    <h4>Lista negra</h4>
    <hr />
    @if (Model.Count() > 0)

    {
        var mailIdentifiers = String.Join(",", Model.Select(i => i.ID).ToArray());
        <table class="table">
            <tr>
                <th>
                    Email
                </th>
                <th>
                    Fecha y hora
                </th>
                <th>
                    Causa
                </th>
                <th>
                    @using (Html.BeginForm("DeleteAll", "BlackList", FormMethod.Post))
                    {
                        @Html.Hidden("mailIdentifiers", mailIdentifiers);
                        <input type="submit" value="Eliminar todas" />
                    }
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.EMAIL)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TIMESTAMP)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.REASON)
                    </td>
                    <td>
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.ID })
                    </td>
                </tr>

            }
        </table>
    }
    else
    {
        <p>La busqueda no ha producido resultados</p>
    }
    <p>@Html.ActionLink("Volver a buscar", "Search")</p>
</body>
</html>

AmazonMail/Views/BlackList/Index.cshtml
@model IEnumerable<AmazonMail.Models.BLACKLIST>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{    
    ViewBag.Title = "Black List";
    var pagedlist = (IPagedList)Model;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lista negra</title>
</head>
<body>

    <h4>Lista negra</h4>
    <hr />
     <p>
        @using (Html.BeginForm("Index", "BlackList", FormMethod.Get))
        {
        <p>
            Buscar por la dirección de correo: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
        }
    </p>          
    <p>
        @Html.ActionLink("Añadir una dirección", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.ReceiverSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Fecha y hora", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>          
            <th>
                Causa
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EMAIL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TIMESTAMP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.REASON)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id=item.ID }) |               
                @Html.ActionLink("Eliminar", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
    </table>
    Página @(pagedlist.PageCount < pagedlist.PageNumber ? 0 : pagedlist.PageNumber) de @pagedlist.PageCount

    @Html.PagedListPager(pagedlist, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</body>
</html>

AmazonMail/Views/BlackList/Search.cshtml
@model IEnumerable<AmazonMail.Models.BLACKLIST>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{    
    ViewBag.Title = "Black List";    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Lista negra</title>
</head>
<body>
    <h4>Lista negra</h4>
    <hr />
    <p>
        @using (Html.BeginForm("Find", "BlackList", FormMethod.Get))
        {
    <p>
        Buscar por direcciones de correo (separadas con comas): @Html.TextArea("searchString", ViewBag.CurrentFilter as string, new { rows = "5", cols = "200" })
        <input type="submit" value="Search" />        
    </p>
        }
    </p>  
</body>
</html>