AmazonMail/Models/MESSAGELOG.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonMail.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGELOG
    {
        public int LOGID { get; set; }
        public string MESSAGEID { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public System.DateTime SENDDATE { get; set; }
        public string APPID { get; set; }
        public string ERRORMESSAGE { get; set; }
        public string SUBJECT { get; set; }
        public string ERRORTYPE { get; set; }
        public string MESSAGE { get; set; }
    }
}

AmazonMail/Controllers/MessageLogController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AmazonMail.Models;
using AmazonMail.Modules;
using PagedList;

using Microsoft.AspNet.Identity;

namespace AmazonMail.Controllers
{
    public class MessageLogController : Controller
    {
        private AmazonDBModel db = new AmazonDBModel();

     
        
        // GET: /MessageLog/
        public ActionResult Index(string hidUpdate, string sortOrder, string currentFilter, string searchString, int? page)
        {
            if(!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            //string strCurrentUserId=System.Web.HttpContext.Current.GetOwinContext().Authentication.User.Identity.GetUserId();
            string strCurrentUserId = User.Identity.GetUserId();        
            IdentityManager idManager = new IdentityManager();
            string strAppId=idManager.GetUserAppId(strCurrentUserId);
            
            
            if (!String.IsNullOrEmpty(hidUpdate))
            {
               //refresh with info from queue
                Queue.RefreshAll();
                //return View(db.MESSAGELOG.OrderByDescending(m => m.SENDDATE).ToList());
            }
            //return View(db.MESSAGELOG.OrderByDescending(m => m.SENDDATE).ToList());
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSortParm = String.IsNullOrEmpty(sortOrder) ? "date_asc" : "";
            ViewBag.ReceiverSortParm = sortOrder == "receiver" ? "receiver_desc" : "receiver";
            ViewBag.AppidSortParm = sortOrder == "appid" ? "appid_desc" : "appid";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            
            var messages = from m in db.MESSAGELOG select m;
            if (strAppId != "SES")
                messages = messages.Where(s => s.APPID == strAppId);

            if (!String.IsNullOrEmpty(searchString))
            {
                messages = messages.Where(s => s.RECEIVER.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "receiver_desc":
                    messages = messages.OrderByDescending(s => s.RECEIVER);
                    break;
                case "receiver":
                    messages = messages.OrderBy(s => s.RECEIVER);
                    break;
                case "appid_desc":
                    messages = messages.OrderByDescending(s => s.APPID);
                    break;
                case "appid":
                    messages = messages.OrderBy(s => s.APPID);
                    break;
                case "date_asc":
                    messages = messages.OrderBy(s => s.SENDDATE);
                    break;
                default:
                    messages = messages.OrderByDescending(s => s.SENDDATE);
                    break;  
            }

            int pageSize = 50;
            int pageNumber = (page ?? 1);
            var mes=messages.ToPagedList(pageNumber, pageSize);

            //calculo las estadisticas
            ViewBag.numSoftBounces = messages.Where(m => m.ERRORTYPE == "SB").Count();
            ViewBag.numHardBounces = messages.Where(m => m.ERRORTYPE == "HB").Count();
            ViewBag.numSpamComplaints = messages.Where(m => m.ERRORTYPE == "SC").Count();
            ViewBag.numOK = messages.Where(m => m.ERRORTYPE == "OK").Count();
            ViewBag.numTotal = messages.Count();
            ViewBag.numBlackListed = messages.Where(m => m.ERRORTYPE == "BL").Count(); 

            return View(mes);
            //return View(messages.ToList());
        }

        // GET: /MessageLog/Details/5
        public ActionResult Details(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MESSAGELOG messagelog = db.MESSAGELOG.Find(id);
            if (messagelog == null)
            {
                return HttpNotFound();
            }
            return View(messagelog);
        }

        // GET: /MessageLog/Create
        public ActionResult Create()
        {
            return View();
           
        }

        // POST: /MessageLog/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="LOGID,MESSAGEID,SENDER,RECEIVER,SENDDATE,APPID,ERRORMESSAGE,SUBJECT")] MESSAGELOG messagelog)
        {
            if (ModelState.IsValid)
            {
                db.MESSAGELOG.Add(messagelog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(messagelog);
        }

        // GET: /MessageLog/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MESSAGELOG messagelog = db.MESSAGELOG.Find(id);
            if (messagelog == null)
            {
                return HttpNotFound();
            }
            return View(messagelog);
        }

        // POST: /MessageLog/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="LOGID,MESSAGEID,SENDER,RECEIVER,SENDDATE,APPID,ERRORMESSAGE,SUBJECT")] MESSAGELOG messagelog)
        {
            if (ModelState.IsValid)
            {
                db.Entry(messagelog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(messagelog);
        }

        // GET: /MessageLog/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MESSAGELOG messagelog = db.MESSAGELOG.Find(id);
            if (messagelog == null)
            {
                return HttpNotFound();
            }
            return View(messagelog);
        }

        // POST: /MessageLog/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MESSAGELOG messagelog = db.MESSAGELOG.Find(id);
            db.MESSAGELOG.Remove(messagelog);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        } 

    }   
}

AmazonMail/Views/MessageLog/Create.cshtml
@model AmazonMail.Models.MESSAGELOG

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messages";    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>MESSAGELOG</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MESSAGEID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MESSAGEID)
                    @Html.ValidationMessageFor(model => model.MESSAGEID)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SENDER, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SENDER)
                    @Html.ValidationMessageFor(model => model.SENDER)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.RECEIVER, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RECEIVER)
                    @Html.ValidationMessageFor(model => model.RECEIVER)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SENDDATE, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SENDDATE)
                    @Html.ValidationMessageFor(model => model.SENDDATE)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.APPID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.APPID)
                    @Html.ValidationMessageFor(model => model.APPID)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ERRORMESSAGE, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ERRORMESSAGE)
                    @Html.ValidationMessageFor(model => model.ERRORMESSAGE)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SUBJECT, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SUBJECT)
                    @Html.ValidationMessageFor(model => model.SUBJECT)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

AmazonMail/Views/MessageLog/Delete.cshtml
@model AmazonMail.Models.MESSAGELOG

@{
   
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messages";    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Eliminar</title>
</head>
<body>
    <h3>¿Esta seguro de que quiere eliminar este registro?</h3>
    <div>
        <h4>Registro de mensajes</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                ID
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MESSAGEID)
            </dd>
    
            <dt>
               Remitente
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SENDER)
            </dd>
    
            <dt>
                Destinatario
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.RECEIVER)
            </dd>
            <dt>
                Asunto
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SUBJECT)
            </dd>
            <dt>
               Fecha de envío
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SENDDATE)
            </dd>
    
            <dt>
                Id de la aplicación
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.APPID)
            </dd>
    
            <dt>
                Error
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ERRORMESSAGE)
            </dd> 
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Eliminar" class="btn btn-default" /> |
                @Html.ActionLink("Volver a la lista de mensajes", "Index")
            </div>
        }
    </div>
</body>
</html>

AmazonMail/Views/MessageLog/Details.cshtml
@model AmazonMail.Models.MESSAGELOG


@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messages";
    //IHtmlString strHtmlInput = Html.Raw(@Model.MESSAGE);
    //String strInput=strHtmlInput.ToString().Replace("'","\'");
    IHtmlString strHtmlInput = new HtmlString(HttpUtility.JavaScriptStringEncode(@Model.MESSAGE));
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Detalles</title>
</head>
<body>
    <div>
        <h4>Registro de mensajes</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                ID
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MESSAGEID)
            </dd>
    
            <dt>
               Remitente
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.SENDER)
            </dd>
    
            <dt>
               Destinatario
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.RECEIVER)
            </dd>
            <dt>
                Asunto
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SUBJECT)
            </dd>
            <dt>
                Contenido
            </dt>
            <dd>
                <iframe id="messageContent" scrolling="auto" width="600" height="200"></iframe>
                <script>var iframe = document.getElementById('messageContent');
                    iframedoc = iframe.contentDocument || iframe.contentWindow.document;                    
                    iframedoc.body.innerHTML = '@strHtmlInput';                    
                </script>
            </dd>
            <dt>
                Fecha de envío
            </dt>    
            <dd>
                @Html.DisplayFor(model => model.SENDDATE)
            </dd>
    
            <dt>
                ID de la aplicación
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.APPID)
            </dd>
    
            <dt>
                Error
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ERRORMESSAGE)
            </dd>
    
        </dl>
    </div>
    <p>        
        @Html.ActionLink("Volver a la lista de mensajes", "Index")
    </p>
</body>
</html>

AmazonMail/Views/MessageLog/Edit.cshtml
@model AmazonMail.Models.MESSAGELOG

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messages";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>MESSAGELOG</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.LOGID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MESSAGEID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MESSAGEID)
                    @Html.ValidationMessageFor(model => model.MESSAGEID)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SENDER, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SENDER)
                    @Html.ValidationMessageFor(model => model.SENDER)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.RECEIVER, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RECEIVER)
                    @Html.ValidationMessageFor(model => model.RECEIVER)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SENDDATE, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SENDDATE)
                    @Html.ValidationMessageFor(model => model.SENDDATE)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.APPID, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.APPID)
                    @Html.ValidationMessageFor(model => model.APPID)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ERRORMESSAGE, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ERRORMESSAGE)
                    @Html.ValidationMessageFor(model => model.ERRORMESSAGE)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.SUBJECT, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SUBJECT)
                    @Html.ValidationMessageFor(model => model.SUBJECT)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

AmazonMail/Views/MessageLog/Index.cshtml
@model IEnumerable<AmazonMail.Models.MESSAGELOG>
@using PagedList;
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Messages";
    var pagedlist = (IPagedList)Model;
 }

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Registro de mensajes</title>
</head>
<body>
    <h4>Registro de mensajes</h4>
    <hr />


    @using (Html.BeginForm("Index", "MessageLog", FormMethod.Get))
    {
        <p>
            Buscar por el destinatario: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
            <input type="submit" value="Search" />
        </p>
    }

    @using (Html.BeginForm("Index", "MessageLog", FormMethod.Get))
    {
        @Html.Hidden("hidUpdate", "Yes")
        <input type="submit" value="Actualizar" />
    }

    <div style="margin-top:50px">
        <b>Estadísticas de envíos (90 días)</b>
        <table class="table">
            <tr><th>Total</th><th>Enviados OK</th><th>Soft Bounces</th><th>Hard Bounces</th><th>Spam Complaints</th><th>Lista negra</th></tr>
            <tr><td>@ViewBag.numTotal</td><td>@ViewBag.numOK</td><td>@ViewBag.numSoftBounces</td><td>@ViewBag.numhardBounces</td><td>@ViewBag.numSpamComplaints</td><td>@ViewBag.numBlackListed</td></tr>
        </table>
    </div>
    Página @(pagedlist.PageCount < pagedlist.PageNumber ? 0 : pagedlist.PageNumber) de @pagedlist.PageCount

    @Html.PagedListPager(pagedlist, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

    <table class="table messagelog">
        <tr>
            <th></th>
            <th>
                ID
            </th>
            <th>
                Remitente
            </th>
            <th>
                @Html.ActionLink("Destinatario", "Index", new { sortOrder = ViewBag.ReceiverSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Asunto
            </th>
            <th>
                @Html.ActionLink("Fecha de envío", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Id de la aplicación", "Index", new { sortOrder = ViewBag.AppidSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                Error
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                @switch (item.ERRORTYPE)
                {
                    case "OK":
                        <td style="color:green;font-weight:bold">@Html.DisplayFor(modelItem => item.ERRORTYPE)</td>
                        break;
                    default:
                        <td style="color:red;font-weight:bold">@Html.DisplayFor(modelItem => item.ERRORTYPE)</td>
                        break;

                }

                <td>
                    @Html.DisplayFor(modelItem => item.MESSAGEID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SENDER)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RECEIVER)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SUBJECT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SENDDATE)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.APPID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ERRORMESSAGE)
                </td>

                <td>
                    @Html.ActionLink("Detalles", "Details", new { id = item.LOGID })
                    @if (User.IsInRole("Admin") || User.IsInRole("CanEdit"))
                    {
                        @Html.ActionLink("Eliminar", "Delete", new { id = item.LOGID })
                    }
                </td>
            </tr>
        }
        <br />
    </table>

    Página @(pagedlist.PageCount < pagedlist.PageNumber ? 0 : pagedlist.PageNumber) de @pagedlist.PageCount

    @Html.PagedListPager(pagedlist, page => Url.Action("Index",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

</body>
</html>